import { User } from '@/app/types';

export const user: User = {
    login: 'ryanlegler',
    id: 1296975,
    node_id: 'MDQ6VXNlcjEyOTY5NzU=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1296975?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ryanlegler',
    html_url: 'https://github.com/ryanlegler',
    followers_url: 'https://api.github.com/users/ryanlegler/followers',
    following_url: 'https://api.github.com/users/ryanlegler/following{/other_user}',
    gists_url: 'https://api.github.com/users/ryanlegler/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/ryanlegler/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ryanlegler/subscriptions',
    organizations_url: 'https://api.github.com/users/ryanlegler/orgs',
    repos_url: 'https://api.github.com/users/ryanlegler/repos',
    events_url: 'https://api.github.com/users/ryanlegler/events{/privacy}',
    received_events_url: 'https://api.github.com/users/ryanlegler/received_events',
    type: 'User',
    site_admin: false,
    name: 'Ryan  Legler',
    company: 'sprinklr',
    blog: '',
    location: 'portland OR',
    email: null,
    hireable: null,
    bio: null,
    twitter_username: 'ryanlegler',
    public_repos: 16,
    public_gists: 14,
    followers: 12,
    following: 130,
    created_at: '2011-12-31T23:40:03Z',
    updated_at: '2023-12-03T20:04:12Z',
};
